# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  USE_DEBUG: '{{if eq .DEBUG "1"}}-debug{{else}}{{end}}'
  USE_TRACY: true
  DLL_EXT: '{{if eq OS "windows"}}dll{{else}}so{{end}}'
  EXE_EXT: '{{exeExt | default ".out"}}'

tasks:
  setup-windows:
    platforms: [windows]
    cmd: packages\\build.bat

  setup-linux:
    platforms: [linux]
    cmd: ./packages/build.sh

  build-meta:
    cmds:
      - |
        odin build engine/meta \
        -build-mode:exe \
        -show-timings \
        -out:out/debug/meta{{.EXE_EXT}} \
        -o:none \
        -use-separate-modules \
    sources:
      - engine/meta/**/*.odin
    generates:
      - out/debug/meta{{.EXE_EXT}}

  run-meta:
    deps: [build-meta]
    cmds:
      - ./out/debug/meta{{.EXE_EXT}} engine

  build-mani:
    cmds:
      - |
        odin build packages/mani/manigen \
        -out:out/debug/mani{{.EXE_EXT}} \
        -show-timings \
        -o:none \
        -collection:packages=packages \
        -ignore-unknown-attributes
    sources:
      - packages/mani/**/*.odin
    generates:
      - out/debug/mani{{.EXE_EXT}}

  run-mani:
    deps: [build-mani]
    cmds:
      - ./out/debug/mani{{.EXE_EXT}} mani_config.json -show-timings
    sources:
      - engine/*.odin
    generates:
      - engine/*_generated.odin

  test:
    deps: [run-meta]
    cmds:
      - |
        odin test engine \
        -define:VALIDATION=true \
        -show-timings \
        -o:none \
        -collection:packages=packages \
        -define:TRACY_ENABLE={{.USE_TRACY}} {{.USE_DEBUG}} \
        -ignore-unknown-attributes

  build:
    deps: [run-meta, run-mani]
    cmds:
      - |
        odin build engine \
        -build-mode:exe -define:VALIDATION=true \
        -show-timings \
        -out:out/debug/engin3{{.EXE_EXT}} \
        -o:none \
        -debug \
        -use-separate-modules \
        -collection:packages=packages \
        -define:TRACY_ENABLE={{.USE_TRACY}} {{.USE_DEBUG}} \
        -ignore-unknown-attributes
    sources:
      - engine/**/*.odin
    generates:
      - out/debug/engin3{{.EXE_EXT}}

  build-no-mani:
    deps: [run-meta]
    cmds:
      - |
        odin build engine \
        -build-mode:exe -define:VALIDATION=true \
        -show-timings \
        -out:out/debug/engin3{{.EXE_EXT}} \
        -o:none \
        -debug \
        -use-separate-modules \
        -collection:packages=packages \
        -define:TRACY_ENABLE={{.USE_TRACY}} {{.USE_DEBUG}} \
        -ignore-unknown-attributes
    sources:
      - engine/**/*.odin
    generates:
      - out/debug/engin3{{.EXE_EXT}}

  run:
    deps: [build]
    cmds:
      - ./out/debug/engin3{{.EXE_EXT}}

  no-mani:
    deps: [build-no-mani]
    cmds:
      - ./out/debug/engin3{{.EXE_EXT}}

  debug:
    platforms: [windows]
    deps: [build]
    cmds:
      - raddbg.exe --profile:engin3.raddbg_profile --auto_run
